name: poolheatercalculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.10
#  flutter_launch: ^0.2.0

  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  intl: ^0.16.1
  dio: ^3.0.9
  rxdart: ^0.24.1
  get_it: ^4.0.2
  bot_toast: ^3.0.0
  shared_preferences: ^0.5.7+3
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.6
  flutter_auth_buttons: ^0.8.0
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  location: ^3.0.2
  charcode: ^1.1.3
  pdf: ^1.8.1
  share: ^0.6.4+3
  flutter_email_sender: ^3.0.1
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.10
  open_file: ^3.0.1
  flutter_open_whatsapp: ^0.1.2



dev_dependencies:
  flutter_launcher_icons: ^0.7.5
flutter_icons:
  image_path: "assets/ncwg_icon.jpg"
  android: true
  ios: true


flutter:

  uses-material-design: true


  assets:
    - images/
    - i18n/

